# Generated by Django 4.0.1 on 2022-01-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emailcheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=32)),
                ('code', models.IntegerField(max_length=11)),
                ('timestamp', models.IntegerField(max_length=11)),
            ],
        ),
    ]
