# Generated by Django 4.0.1 on 2022-01-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailcheck', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('type', models.CharField(blank=True, max_length=32, null=True)),
                ('relation', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=32, null=True)),
                ('password', models.CharField(blank=True, max_length=64, null=True)),
                ('simulate_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='emailcheck',
            name='id',
        ),
        migrations.AlterField(
            model_name='emailcheck',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailcheck',
            name='email',
            field=models.CharField(blank=True, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emailcheck',
            name='timestamp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
