# Generated by Django 4.0.1 on 2022-01-30 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailcheck', '0002_enterprise_remove_emailcheck_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enterprise',
        ),
    ]
