# Generated by Django 4.0.1 on 2022-01-30 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailcheck', '0003_delete_enterprise'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emailcheck',
            table='Emailcheck',
        ),
    ]
